name: Deploy to AWS (Server Directory Only)

on:
  push:
    paths:
      - 'server/**' 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1 

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        known_hosts: '13.202.118.172 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILYd7RtY/hxGRI19NnSrsNA5FgfsQd1Y3WzGZu7je4rT'

    - name: Clear existing files in 'api' directory (optional)
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@13.202.118.172 'sudo rm -rf /var/www/html/api/*' 

    # - name: Ensure 'api/v1' directory exists and has correct permissions
      # run: |
        #ssh -o StrictHostKeyChecking=no ubuntu@13.202.118.172 'sudo mkdir -p /var/www/html/api/v1 && sudo chown -R www-data:www-data /var/www/html/api && sudo chmod -R 775 /var/www/html/api'

    - name: Deploy to EC2
      run: |
        # Copy files directly to the 'api' directory
        scp -o StrictHostKeyChecking=no -r server/* ubuntu@13.202.118.172:/var/www/html/api
        ssh -o StrictHostKeyChecking=no ubuntu@13.202.118.172 'sudo chown -R www-data:www-data /var/www/html/api/*'
        ssh -o StrictHostKeyChecking=no ubuntu@13.202.118.172 'sudo systemctl restart apache2'
