name: Deploy to AWS (Server Directory Only)

on:
  push:
    paths:
      - 'server/**' 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1 

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key:  ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        known_hosts: '|3.108.54.205 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCVu3WedyL1d/DxyD0xksXCJw7Yh+cRaa9LGfwCtLcoeWj1MR9NddEZhp4B9dwQnx9Bt1Xe40xk9cGb6lEjtrz+BSaUbzxGLJyXVwq+tSZhI9egodwuQNZEtFda2lL/TeidWBmRhLTrM7vRCNvXqvqd5RrKKMEUjA0nKScZiNRIfekknTjGxIQqrd4/QHokNsVNJFOAksRGXeeYupG4v6ZK6D1JgwdIn4078GjsIWC0l+bDAWHxDYAx0ciBvZsiIoC0s5TFQNr5w8otlVTkRHy9YjHjGBn+cO3i1GXUeOYJI9PdiVvrl5ai/3S1DWdlBSafKsflaqF4zZoGvTL6N00d'

    - name: Clear existing files in web root (optional)
      run: |
        ssh -o StrictHostKeyChecking=no dpapi@3.108.54.205 'sudo rm -rf /var/www/html/api/*' 

    - name: Deploy to EC2
      run: |
        # Create the 'api' directory if it doesn't exist (using sudo)
        ssh -o StrictHostKeyChecking=no dpapi@3.108.54.205 'sudo mkdir -p /var/www/html/api'
        # Set ownership and permissions for the 'api' directory
        ssh -o StrictHostKeyChecking=no dpapi@3.108.54.205 'sudo chown -R www-data:www-data /var/www/html/api'
        ssh -o StrictHostKeyChecking=no dpapi@3.108.54.205 'sudo chmod -R 775 /var/www/html/api'
        # Copy files to the 'api' directory
        scp -o StrictHostKeyChecking=no -r server/* dpapi@3.108.54.205:/var/www/html/api/
        ssh -o StrictHostKeyChecking=no dpapi@3.108.54.205 'sudo systemctl restart apache2'
